### ISSUE TITLE
Exception when starting JAR

### ISSUE THREAD

**Issue by mvmn** [s12v/sns#22]
I'm running a JAR file this way `DB_PATH=~/tmp/snsdb.json java -jar ~/_my/_prog/_dev/sns-0.1.2.jar`, and it seems to fail with these exceptions:

```
[WARN] [03/17/2017 20:47:49.820] [main] [EventStream(akka://sns)] Logger log1-Slf4jLogger did not respond within Timeout(5000 milliseconds) to InitializeLogger(bus)
error while starting up loggers
akka.ConfigurationException: Logger specified in config can't be loaded [akka.event.slf4j.Slf4jLogger] due to [akka.event.Logging$LoggerInitializationException: Logger log1-Slf4jLogger did not respond with LoggerInitialized, sent instead [TIMEOUT]]
	at akka.event.LoggingBus$$anonfun$4$$anonfun$apply$1.applyOrElse(Logging.scala:118)
	at akka.event.LoggingBus$$anonfun$4$$anonfun$apply$1.applyOrElse(Logging.scala:117)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:216)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Failure.recover(Try.scala:216)
	at akka.event.LoggingBus$$anonfun$4.apply(Logging.scala:117)
	at akka.event.LoggingBus$$anonfun$4.apply(Logging.scala:112)
	at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:683)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:682)
	at akka.event.LoggingBus$class.startDefaultLoggers(Logging.scala:112)
	at akka.event.EventStream.startDefaultLoggers(EventStream.scala:28)
	at akka.actor.LocalActorRefProvider.init(ActorRefProvider.scala:667)
	at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:648)
	at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:645)
	at akka.actor.ActorSystemImpl._start(ActorSystem.scala:645)
	at akka.actor.ActorSystemImpl.start(ActorSystem.scala:661)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:142)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:109)
	at me.snov.sns.Main$.delayedEndpoint$me$snov$sns$Main$1(Main.scala:21)
	at me.snov.sns.Main$delayedInit$body.apply(Main.scala:20)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at me.snov.sns.Main$.main(Main.scala:20)
	at me.snov.sns.Main.main(Main.scala)
Caused by: akka.event.Logging$LoggerInitializationException: Logger log1-Slf4jLogger did not respond with LoggerInitialized, sent instead [TIMEOUT]
	at akka.event.LoggingBus$class.akka$event$LoggingBus$$addLogger(Logging.scala:187)
	at akka.event.LoggingBus$$anonfun$4$$anonfun$apply$4.apply(Logging.scala:116)
	at akka.event.LoggingBus$$anonfun$4$$anonfun$apply$4.apply(Logging.scala:115)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Success.map(Try.scala:237)
	at akka.event.LoggingBus$$anonfun$4.apply(Logging.scala:115)
	... 27 more
Exception in thread "main" akka.ConfigurationException: Could not start logger due to [akka.ConfigurationException: Logger specified in config can't be loaded [akka.event.slf4j.Slf4jLogger] due to [akka.event.Logging$LoggerInitializationException: Logger log1-Slf4jLogger did not respond with LoggerInitialized, sent instead [TIMEOUT]]]
	at akka.event.LoggingBus$class.startDefaultLoggers(Logging.scala:146)
	at akka.event.EventStream.startDefaultLoggers(EventStream.scala:28)
	at akka.actor.LocalActorRefProvider.init(ActorRefProvider.scala:667)
	at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:648)
	at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:645)
	at akka.actor.ActorSystemImpl._start(ActorSystem.scala:645)
	at akka.actor.ActorSystemImpl.start(ActorSystem.scala:661)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:142)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:109)
	at me.snov.sns.Main$.delayedEndpoint$me$snov$sns$Main$1(Main.scala:21)
	at me.snov.sns.Main$delayedInit$body.apply(Main.scala:20)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at me.snov.sns.Main$.main(Main.scala:20)
	at me.snov.sns.Main.main(Main.scala)
20:47:50.024 [sns-akka.actor.default-dispatcher-4] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
```

**Comment by mvmn** [comment]
P.S. Workaround for this - add a `akka.logger-startup-timeout` JVM system property when starting:
```java -Dakka.logger-startup-timeout=30s -jar sns-0.1.3.jar```

**Comment by ebmeierj** [comment]
Thanks for this ^^^! I've been trying to figure out where to configure that.
